# Generated by Django 3.2 on 2022-03-01 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='teacher name'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='assignment title'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='choice title'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=2000, verbose_name='question')),
                ('order', models.IntegerField(blank=True, verbose_name='order')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.choice')),
                ('assignment', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='api.assignment')),
                ('choices', models.ManyToManyField(to='api.Choice')),
            ],
        ),
    ]
