# Generated by Django 3.2 on 2022-02-08 19:19

import schoole_system.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', schoole_system.authentication.models.UserManager()),
            ],
        ),
    ]
