version: "3.9"
   
services: 
  web:
    build:
      context: .
    command: uwsgi --http :8000 --module configuration.wsgi

    volumes:
      - .:/app
    expose:
      - 8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=schoole_system_db_main
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j
    depends_on:
        - db 
  db:
    image: postgres:14.1
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - postgres_db=schoole_system_db_main
      - postgres_user=kirill
      - postgres_password=password
    ports:
      - "5432:5432"
  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A configuration worker --loglevel=info --without-gossip --without-mingle --without-heartbeat -Ofair
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=schoole_system_db_main
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    command: celery -A configuration beat -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=schoole_system_db_main
      - POSTGRES_USER=kirill
      - POSTGRES_PASSWORD=password
      - ALLOWED_HOSTS=*
      - SECRET_KEY=vvno_hiu+6-qbv8+4_kxly8@6@a9#(_681ewc&)fe*75u-j6+j
    depends_on:
      - redis
      - web

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web 

networks:
    djangonetwork:
      driver: bridge
